#!/bin/bash
# Theme application engine
# Usage: apply-theme.sh <theme-name>

THEME="$1"
THEMES_DIR="$HOME/.config/themes"
THEME_DIR="$THEMES_DIR/$THEME"

if [[ -z "$THEME" || ! -f "$THEME_DIR/theme.conf" ]]; then
  notify-send -t 3000 "Theme Error" "Theme '$THEME' not found"
  exit 1
fi

# Source the theme variables
source "$THEME_DIR/theme.conf"

# ── UI effect flags (decoupled from the theme, and from each other) ─────
# Two independent on/off flags layered on top of the theme:
#   glass          — frosted glass: translucent surfaces. Off => opaque.
#   elephant-focus — blur the whole desktop behind the walker launcher. Off =>
#                    no backdrop scrim.
GLASS="$(cat "$HOME/.local/state/sharkos/glass" 2>/dev/null || echo on)"
FOCUS="$(cat "$HOME/.local/state/sharkos/elephant-focus" 2>/dev/null || echo on)"

# Terminal background translucency (frosted glass on ghostty). A theme may
# override TERM_OPACITY in its theme.conf; otherwise default to a readable 0.85.
TERM_OPACITY="${TERM_OPACITY:-0.85}"

# ── GTK light/dark ──────────────────────────────────────────────────────
# GTK apps (Thunar, pavucontrol) only get Adwaita light or dark from us, picked
# from the theme's background luminance (Rec. 709) so the light themes
# (catppuccin-latte, flexoki-light, white) don't leave Thunar dark. Unparseable
# or missing COLOR_BG falls back to dark, matching the noir default.
gtk_prefer_dark() {
  local hex="${COLOR_BG#\#}" r g b lum
  [[ "$hex" =~ ^[0-9A-Fa-f]{6}$ ]] || { echo 1; return; }
  r=$((16#${hex:0:2})); g=$((16#${hex:2:2})); b=$((16#${hex:4:2}))
  lum=$(((2126 * r + 7152 * g + 722 * b) / 10000))
  ((lum < 128)) && echo 1 || echo 0
}
GTK_PREFER_DARK="$(gtk_prefer_dark)"
if [[ "$GTK_PREFER_DARK" == "1" ]]; then
  GTK_COLOR_SCHEME="prefer-dark"
  GTK_THEME_NAME="Adwaita-dark"
else
  GTK_COLOR_SCHEME="prefer-light"
  GTK_THEME_NAME="Adwaita"
fi

# UI Glass off: force the window/panel backgrounds opaque (strip the alpha).
if [[ "$GLASS" == "off" ]]; then
  # rgba(r, g, b, a) -> rgba(r, g, b, 1)
  WINDOW_BG="$(sed -E 's/,[[:space:]]*[0-9.]+\)/, 1)/' <<<"$WINDOW_BG")"
  WINDOW_BG_SOLID="$(sed -E 's/,[[:space:]]*[0-9.]+\)/, 1)/' <<<"$WINDOW_BG_SOLID")"
  TERM_OPACITY="1"
fi

# Elephant focus: a faint full-screen scrim behind walker. walker's layer covers
# the whole monitor, so this (with the low ignore_alpha for the walker
# namespace) lets the blur frost the entire desktop behind the launcher — a soft
# focus effect. 0.25 clears the blur threshold and gives a gentle dim without
# heavily darkening. Independent of glass.
if [[ "$FOCUS" == "off" ]]; then
  WALKER_SCRIM="transparent"
else
  # Keep waybar (top, ~38px) in focus while leaving the launcher box untouched:
  # a gradient scrim that's transparent for the top bar strip and the dim/blur
  # colour below. Using a gradient (not window padding) means the box isn't
  # shifted or clipped — padding would inset the centred box and cut its bottom.
  WALKER_BAR_STRIP="45px"
  WALKER_SCRIM="linear-gradient(to bottom, transparent ${WALKER_BAR_STRIP}, rgba(0, 0, 0, 0.25) ${WALKER_BAR_STRIP})"
fi

# Hyprland blur master: on if EITHER frosted glass or elephant focus needs it,
# off only when both are off. This is what lets elephant focus blur the desktop
# even with glass off (opaque surfaces simply hide the blur, so glass-off still
# looks solid).
if [[ "$GLASS" == "off" && "$FOCUS" == "off" ]]; then
  BLUR_ENABLED="false"
else
  BLUR_ENABLED="true"
fi
# The Hyprland blur master switch lives in a sourced file so it can be flipped
# without editing hyprland.conf (which sources it). Disabling it kills blur on
# windows AND layer surfaces (waybar/walker/swaync/swayosd).
mkdir -p "$HOME/.config/hypr"
cat > "$HOME/.config/hypr/glass.conf" <<EOF
# Generated by apply-theme.sh from ~/.local/state/sharkos/glass — do not edit.
decoration {
    blur {
        enabled = $BLUR_ENABLED
    }
}
EOF

apply_template() {
  local tpl="$1"
  local target="$2"
  local content
  content=$(<"$tpl")

  # Replace all {{VAR}} with the value of $VAR
  local var
  while [[ "$content" =~ \{\{([A-Za-z_0-9]+)\}\} ]]; do
    var="${BASH_REMATCH[1]}"
    content="${content//"{{$var}}"/"${!var}"}"
  done

  echo "$content" > "$target"
}

notify-send -t 2000 "Applying theme..." "${THEME_NAME:-$THEME}"

# Apply each template
apply_template "$THEMES_DIR/templates/walker-style.css.tpl" \
  "$HOME/.config/walker/themes/noir/style.css"

apply_template "$THEMES_DIR/templates/hyprland-colors.conf.tpl" \
  "$HOME/.config/hypr/colors.conf"

apply_template "$THEMES_DIR/templates/waybar-style.css.tpl" \
  "$HOME/.config/waybar/style.css"

apply_template "$THEMES_DIR/templates/swaync.css.tpl" \
  "$HOME/.config/swaync/style.css"

apply_template "$THEMES_DIR/templates/jolt.toml.tpl" \
  "$HOME/.config/jolt/themes/sharkos.toml"

apply_template "$THEMES_DIR/templates/ghostty.conf.tpl" \
  "$HOME/.config/ghostty/config"

apply_template "$THEMES_DIR/templates/hyprlock.conf.tpl" \
  "$HOME/.config/hypr/hyprlock.conf"

apply_template "$THEMES_DIR/templates/swayosd-style.css.tpl" \
  "$HOME/.config/swayosd/style.css"

apply_template "$THEMES_DIR/templates/btop.theme.tpl" \
  "$HOME/.config/btop/themes/sharkos.theme"

apply_template "$THEMES_DIR/templates/nvim-colors.lua.tpl" \
  "$HOME/.config/nvim/lua/sharkos_palette.lua"

# GTK 3 + 4. These live outside the symlinked repo configs (they're per-machine
# rendered state, and ~/.config/gtk-*/ is GTK's own directory), so they're
# written straight into $HOME rather than through config/.
mkdir -p "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"
apply_template "$THEMES_DIR/templates/gtk-settings.ini.tpl" \
  "$HOME/.config/gtk-3.0/settings.ini"
apply_template "$THEMES_DIR/templates/gtk-settings.ini.tpl" \
  "$HOME/.config/gtk-4.0/settings.ini"

# Portal clients (libadwaita, Chromium, Electron, Flatpak) don't read
# settings.ini — they ask xdg-desktop-portal-gtk, which reads these gsettings
# keys. Hence the explicit -dark theme name here: there's no prefer-dark flag on
# this path, the variant has to be named.
if command -v gsettings >/dev/null 2>&1; then
  gsettings set org.gnome.desktop.interface color-scheme "$GTK_COLOR_SCHEME" 2>/dev/null || true
  gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME_NAME" 2>/dev/null || true
fi

# Live-reload the palette in any running Neovim. Best-effort: nvim opens a
# default RPC socket at $XDG_RUNTIME_DIR/nvim.<pid>.0; tell each to re-read the
# regenerated palette. Harmless if none are running or nvim isn't installed.
if command -v nvim >/dev/null 2>&1; then
  for sock in "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"/nvim.*; do
    [[ -S "$sock" ]] || continue
    nvim --server "$sock" --remote-send '<C-\><C-N>:SharkReloadTheme<CR>' >/dev/null 2>&1 || true
  done
fi

# Set the theme's wallpaper, if it defines one (empty = leave current wallpaper alone)
if [[ -n "${WALLPAPER:-}" && -f "$WALLPAPER" ]]; then
  # Persist for next login
  cat > "$HOME/.config/hypr/hyprpaper.conf" <<EOF
preload = $WALLPAPER

wallpaper {
    monitor =
    path = $WALLPAPER
}
splash = false
EOF
  # hyprpaper is restarted by reload-ui.sh below to pick up this config.
fi

# Record current theme
echo "$THEME" > "$THEMES_DIR/.current"

# Reload all UI components
"$HOME/.config/hypr/scripts/reload-ui.sh"
