#!/bin/bash
# Theme application engine
# Usage: apply-theme.sh <theme-name>

THEME="$1"
THEMES_DIR="$HOME/.config/themes"
THEME_DIR="$THEMES_DIR/$THEME"

if [[ -z "$THEME" || ! -f "$THEME_DIR/theme.conf" ]]; then
  notify-send -t 3000 "Theme Error" "Theme '$THEME' not found"
  exit 1
fi

# Source the theme variables
source "$THEME_DIR/theme.conf"

# ── UI effect flags (decoupled from the theme, and from each other) ─────
# Two independent on/off flags layered on top of the theme:
#   glass          — frosted glass: translucent surfaces. Off => opaque.
#   elephant-focus — blur the whole desktop behind the walker launcher. Off =>
#                    no backdrop scrim.
GLASS="$(cat "$HOME/.local/state/sharkos/glass" 2>/dev/null || echo on)"
FOCUS="$(cat "$HOME/.local/state/sharkos/elephant-focus" 2>/dev/null || echo on)"

# Terminal background translucency (frosted glass on ghostty). A theme may
# override TERM_OPACITY in its theme.conf; otherwise default to a readable 0.85.
TERM_OPACITY="${TERM_OPACITY:-0.85}"

# UI Glass off: force the window/panel backgrounds opaque (strip the alpha).
if [[ "$GLASS" == "off" ]]; then
  # rgba(r, g, b, a) -> rgba(r, g, b, 1)
  WINDOW_BG="$(sed -E 's/,[[:space:]]*[0-9.]+\)/, 1)/' <<<"$WINDOW_BG")"
  WINDOW_BG_SOLID="$(sed -E 's/,[[:space:]]*[0-9.]+\)/, 1)/' <<<"$WINDOW_BG_SOLID")"
  TERM_OPACITY="1"
fi

# Elephant focus: a faint full-screen scrim behind walker. walker's layer covers
# the whole monitor, so this (with the low ignore_alpha for the walker
# namespace) lets the blur frost the entire desktop behind the launcher — a soft
# focus effect. 0.25 clears the blur threshold and gives a gentle dim without
# heavily darkening. Independent of glass.
if [[ "$FOCUS" == "off" ]]; then
  WALKER_SCRIM="transparent"
else
  # Keep waybar (top, ~38px) in focus while leaving the launcher box untouched:
  # a gradient scrim that's transparent for the top bar strip and the dim/blur
  # colour below. Using a gradient (not window padding) means the box isn't
  # shifted or clipped — padding would inset the centred box and cut its bottom.
  WALKER_BAR_STRIP="45px"
  WALKER_SCRIM="linear-gradient(to bottom, transparent ${WALKER_BAR_STRIP}, rgba(0, 0, 0, 0.25) ${WALKER_BAR_STRIP})"
fi

# Hyprland blur master: on if EITHER frosted glass or elephant focus needs it,
# off only when both are off. This is what lets elephant focus blur the desktop
# even with glass off (opaque surfaces simply hide the blur, so glass-off still
# looks solid).
if [[ "$GLASS" == "off" && "$FOCUS" == "off" ]]; then
  BLUR_ENABLED="false"
else
  BLUR_ENABLED="true"
fi
# The Hyprland blur master switch lives in a sourced file so it can be flipped
# without editing hyprland.conf (which sources it). Disabling it kills blur on
# windows AND layer surfaces (waybar/walker/swaync/swayosd).
mkdir -p "$HOME/.config/hypr"
cat > "$HOME/.config/hypr/glass.conf" <<EOF
# Generated by apply-theme.sh from ~/.local/state/sharkos/glass — do not edit.
decoration {
    blur {
        enabled = $BLUR_ENABLED
    }
}
EOF

apply_template() {
  local tpl="$1"
  local target="$2"
  local content
  content=$(<"$tpl")

  # Replace all {{VAR}} with the value of $VAR
  local var
  while [[ "$content" =~ \{\{([A-Za-z_0-9]+)\}\} ]]; do
    var="${BASH_REMATCH[1]}"
    content="${content//"{{$var}}"/"${!var}"}"
  done

  echo "$content" > "$target"
}

notify-send -t 2000 "Applying theme..." "${THEME_NAME:-$THEME}"

# Apply each template
apply_template "$THEMES_DIR/templates/walker-style.css.tpl" \
  "$HOME/.config/walker/themes/noir/style.css"

apply_template "$THEMES_DIR/templates/hyprland-colors.conf.tpl" \
  "$HOME/.config/hypr/colors.conf"

apply_template "$THEMES_DIR/templates/waybar-style.css.tpl" \
  "$HOME/.config/waybar/style.css"

apply_template "$THEMES_DIR/templates/swaync.css.tpl" \
  "$HOME/.config/swaync/style.css"

apply_template "$THEMES_DIR/templates/jolt.toml.tpl" \
  "$HOME/.config/jolt/themes/sharkos.toml"

apply_template "$THEMES_DIR/templates/ghostty.conf.tpl" \
  "$HOME/.config/ghostty/config"

apply_template "$THEMES_DIR/templates/hyprlock.conf.tpl" \
  "$HOME/.config/hypr/hyprlock.conf"

apply_template "$THEMES_DIR/templates/swayosd-style.css.tpl" \
  "$HOME/.config/swayosd/style.css"

apply_template "$THEMES_DIR/templates/btop.theme.tpl" \
  "$HOME/.config/btop/themes/sharkos.theme"

# Set the theme's wallpaper, if it defines one (empty = leave current wallpaper alone)
if [[ -n "${WALLPAPER:-}" && -f "$WALLPAPER" ]]; then
  # Persist for next login
  cat > "$HOME/.config/hypr/hyprpaper.conf" <<EOF
preload = $WALLPAPER

wallpaper {
    monitor =
    path = $WALLPAPER
}
splash = false
EOF
  # hyprpaper is restarted by reload-ui.sh below to pick up this config.
fi

# Record current theme
echo "$THEME" > "$THEMES_DIR/.current"

# Reload all UI components
"$HOME/.config/hypr/scripts/reload-ui.sh"
