# sharkOS btop theme — generated by apply-theme.sh from the active theme.conf.
# Do not edit; changes are overwritten on the next theme switch.
#
# Built from the terminal palette (COLOR_BG/FG, COLOR_0..15) which every sharkOS
# theme defines, so btop stays in sync with whatever theme is selected.

# Main
theme[main_bg]="#{{COLOR_BG}}"
theme[main_fg]="#{{COLOR_FG}}"
theme[title]="#{{COLOR_FG}}"
theme[hi_fg]="#{{COLOR_4}}"
theme[selected_bg]="#{{COLOR_8}}"
theme[selected_fg]="#{{COLOR_FG}}"
theme[inactive_fg]="#{{COLOR_8}}"
theme[graph_text]="#{{COLOR_7}}"
theme[meter_bg]="#{{COLOR_8}}"
theme[proc_misc]="#{{COLOR_6}}"

# Boxes and dividers
theme[cpu_box]="#{{COLOR_8}}"
theme[mem_box]="#{{COLOR_8}}"
theme[net_box]="#{{COLOR_8}}"
theme[proc_box]="#{{COLOR_8}}"
theme[div_line]="#{{COLOR_8}}"

# Temperature gradient (cool -> warm -> hot)
theme[temp_start]="#{{COLOR_2}}"
theme[temp_mid]="#{{COLOR_3}}"
theme[temp_end]="#{{COLOR_1}}"

# CPU load gradient
theme[cpu_start]="#{{COLOR_2}}"
theme[cpu_mid]="#{{COLOR_3}}"
theme[cpu_end]="#{{COLOR_1}}"

# Memory: free / cached / available / used
theme[free_start]="#{{COLOR_4}}"
theme[free_mid]=""
theme[free_end]="#{{COLOR_12}}"
theme[cached_start]="#{{COLOR_6}}"
theme[cached_mid]=""
theme[cached_end]="#{{COLOR_14}}"
theme[available_start]="#{{COLOR_3}}"
theme[available_mid]=""
theme[available_end]="#{{COLOR_11}}"
theme[used_start]="#{{COLOR_1}}"
theme[used_mid]=""
theme[used_end]="#{{COLOR_9}}"

# Network: download / upload
theme[download_start]="#{{COLOR_4}}"
theme[download_mid]="#{{COLOR_6}}"
theme[download_end]="#{{COLOR_2}}"
theme[upload_start]="#{{COLOR_1}}"
theme[upload_mid]="#{{COLOR_5}}"
theme[upload_end]="#{{COLOR_3}}"

# Process list gradient
theme[process_start]="#{{COLOR_2}}"
theme[process_mid]="#{{COLOR_3}}"
theme[process_end]="#{{COLOR_1}}"
