# Generated by apply-theme.sh — do not edit.
#
# GTK apps (Thunar, pavucontrol, ...) can't be palette-templated like the rest
# of the stack, so instead they follow the light/dark variant of Adwaita that
# matches the active sharkOS theme. Rendered to BOTH ~/.config/gtk-3.0/ and
# ~/.config/gtk-4.0/ — GTK watches this file, so running apps re-theme live.
#
# gtk-theme-name stays "Adwaita" in both cases: the dark variant is selected by
# gtk-application-prefer-dark-theme, which is the toolkit's own switch and works
# for GTK3 (Thunar) and non-libadwaita GTK4 alike.
[Settings]
gtk-theme-name=Adwaita
gtk-icon-theme-name=Adwaita
gtk-application-prefer-dark-theme={{GTK_PREFER_DARK}}
