-- sharkOS Neovim palette — generated by apply-theme.sh from the active
-- theme.conf. Do not edit; overwritten on every theme switch.
--
-- A base16 palette built from the theme's terminal colours (COLOR_BG/FG,
-- COLOR_0..15). base16-nvim expands this into the full editor colourscheme, so
-- Neovim matches whatever sharkOS theme is selected.
--
--   base00 bg   base01 lighter bg   base02 selection   base03 comments
--   base04/06 dim fg   base05 fg   base07 bright fg
--   base08 red  base09 orange  base0A yellow  base0B green
--   base0C cyan base0D blue    base0E magenta base0F special
return {
  base00 = "#{{COLOR_BG}}",
  base01 = "#{{COLOR_0}}",
  base02 = "#{{COLOR_8}}",
  base03 = "#{{COLOR_8}}",
  base04 = "#{{COLOR_7}}",
  base05 = "#{{COLOR_FG}}",
  base06 = "#{{COLOR_7}}",
  base07 = "#{{COLOR_15}}",
  base08 = "#{{COLOR_1}}",
  base09 = "#{{COLOR_9}}",
  base0A = "#{{COLOR_3}}",
  base0B = "#{{COLOR_2}}",
  base0C = "#{{COLOR_6}}",
  base0D = "#{{COLOR_4}}",
  base0E = "#{{COLOR_5}}",
  base0F = "#{{COLOR_1}}",
}
