// Generated by apply-theme.sh from templates/quickshell-theme.qml.tpl — do not edit.
import QtQuick

QtObject {
    readonly property string wallpaper: "{{WALLPAPER_RESOLVED}}"
    readonly property string accent: "{{ACCENT_HEX}}"
    readonly property string fg: "{{FG_COLOR}}"
    readonly property string glassTint: "{{GLASS_TINT}}"
}
