// Generated by apply-theme.sh from templates/quickshell-theme.qml.tpl — do not edit.
// (This committed copy carries the LiquidAss (Beta) defaults.)
import QtQuick

QtObject {
    readonly property string wallpaper: "/home/sharkey/Git/sharkOS/wallpaper/LOGO_BETA.jpg"
    readonly property string accent: "#7fd8e8"
    readonly property string fg: "#ffffff"
    readonly property string glassTint: "#4d0a1418"
}
